version: "3.7"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8229
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8229
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - pg-network
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    networks:
      - pg-network
  pgadmin:
    container_name: pgadmin_masoul_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mas_oul
      PGADMIN_DEFAULT_PASSWORD: Volkeno@2024!
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pg-network
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 5223:80
    depends_on:
      - web
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: