# Generated by Django 3.1.14 on 2024-01-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240123_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cni',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ninea',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_cr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deletion_type',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('visiteur', 'visiteur'), ('vendeur', 'vendeur'), ('admin', 'admin'), ('superadmin', 'superadmin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('visiteur', 'visiteur'), ('vendeur', 'vendeur'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='user', max_length=50),
        ),
    ]
