# Generated by Django 3.1.14 on 2024-01-30 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240130_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='status',
            field=models.CharField(choices=[('drafted', 'drafted'), ('published', 'published')], default='published', max_length=50),
        ),
        migrations.CreateModel(
            name='AchatVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, editable=False)),
                ('paid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='api.voucher')),
            ],
        ),
    ]
