# Generated by Django 3.1.14 on 2024-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240130_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(blank=True, choices=[('achat_voucher', 'achat_voucher')], max_length=50),
        ),
    ]
