# Generated by Django 3.1.14 on 2024-01-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240131_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(blank=True, choices=[('achat_voucher', 'achat_voucher'), ('commande', 'commande')], max_length=50),
        ),
    ]
