# Generated by Django 3.1.14 on 2024-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240131_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(choices=[('argent', 'argent'), ('mixte', 'mixte')], default='mixte', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
