# Generated by Django 3.1.14 on 2024-02-05 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('[\\d,+]', 'This field must be number only', 'Invalid field')]),
        ),
    ]
