# Generated by Django 3.1.14 on 2024-02-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_configpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configpoint',
            old_name='point',
            new_name='points',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_afficher',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
