# Generated by Django 3.1.14 on 2024-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20240207_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deletion_type',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('vendeur', 'vendeur'), ('admin', 'admin'), ('superadmin', 'superadmin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('vendeur', 'vendeur'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='user', max_length=50),
        ),
    ]
