# Generated by Django 3.1.14 on 2024-02-09 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_categorie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, editable=False)),
                ('nom', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=1000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='api.categorie')),
            ],
        ),
    ]
