# Generated by Django 3.1.14 on 2024-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(blank=True, choices=[('achat_voucher', 'achat_voucher'), ('commande', 'commande'), ('sharing', 'sharing')], max_length=50),
        ),
    ]
