# Generated by Django 3.1.14 on 2024-02-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20240212_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
