# Generated by Django 3.1.14 on 2024-02-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_produit_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
