# Generated by Django 3.1.14 on 2024-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_afficher',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
