# Generated by Django 3.1.14 on 2024-02-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_messageaccueil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(choices=[('CGU', 'CGU'), ('ACCUEIL', 'ACCUEIL')], default='CGU', max_length=50),
        ),
    ]
